apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: basic3tier
  name: basic3tier-api
  namespace: basic3tier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic3tier
  template:
    metadata:
      labels:
        app: basic3tier
    spec:
      containers:
      - image: 517344335201.dkr.ecr.ap-southeast-2.amazonaws.com/codingdojo_ecr:basic3tier-api
        name: basic3tier-api      
        ports:
        - containerPort: 81
          name: basic3tier-api
      imagePullSecrets:
       - name: regcred