apiVersion: v1
kind: Service
metadata:
  labels:
    app: basic3tier
  name: basic3tier-api
  namespace: basic3tier
spec:
  type: ClusterIP
  ports:
  - name: "basic3tier-api"
    port: 8080
    targetPort: 8080
  selector:
    app: basic3tier
  