apiVersion: v1
kind: Service
metadata:
  labels:
    app: basic3tier
  name: basic3tier-ui-service
  namespace: basic3tier
spec:
  type: NodePort
  ports:
  - name: "frontend-service"
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: basic3tier