apiVersion: v1
kind: Service
metadata:
  name: basic3tier
  namespace: basic3tier
spec:
  type: NodePort  
  selector:
    app: basic3tier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080