apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic3tier
  namespace: basic3tier
spec:
  ingressClassName: 'nginx'
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: basic3tier-ui-service
            port:
              number: 80